import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#e5b5ff",
        "surface-container-highest": "#353439",
        "on-primary-container": "#fffdff",
        background: "#131317",
        "border-glass": "rgba(255, 255, 255, 0.06)",
        "primary-fixed": "#f2daff",
        "tertiary-fixed": "#ffdf9a",
        "status-error": "#FF4A4A",
        "tertiary-container": "#947000",
        "text-muted": "#8A8A93",
        "surface-container-high": "#2a292e",
        "on-secondary-container": "#d9a4f8",
        surface: "#131317",
        "on-secondary": "#481965",
        "terminal-bg": "#050508",
        "surface-tint": "#e0b6ff",
        "on-surface": "#e4e1e7",
        "outline-variant": "#4d4353",
        "on-tertiary-fixed": "#251a00",
        "on-error": "#690005",
        "on-primary-fixed": "#2e004e",
        "surface-container-low": "#1b1b1f",
        "surface-dim": "#131317",
        "surface-glass-modal": "rgba(20, 20, 28, 0.7)",
        "on-primary-fixed-variant": "#6a0baa",
        primary: "#e0b6ff",
        tertiary: "#edc156",
        "inverse-on-surface": "#303034",
        "surface-container-lowest": "#0e0e12",
        "surface-variant": "#353439",
        "on-primary": "#4c007d",
        "surface-glass-heavy": "rgba(20, 20, 28, 0.6)",
        "on-tertiary-container": "#fffdff",
        "on-secondary-fixed": "#30004b",
        "on-background": "#e4e1e7",
        secondary: "#e5b5ff",
        "surface-container": "#1f1f24",
        "text-primary": "#EAEAEA",
        "on-secondary-fixed-variant": "#60327d",
        "surface-bright": "#39393d",
        "tertiary-fixed-dim": "#edc156",
        "inverse-surface": "#e4e1e7",
        "on-tertiary": "#3f2e00",
        "on-surface-variant": "#d0c2d5",
        "surface-glass": "rgba(20, 20, 28, 0.4)",
        outline: "#998d9e",
        "on-tertiary-fixed-variant": "#5a4300",
        "secondary-fixed": "#f4d9ff",
        "primary-fixed-dim": "#e0b6ff",
        "secondary-container": "#633480",
        "error-container": "#93000a",
        "inverse-primary": "#8433c4",
        "on-error-container": "#ffdad6",
        "primary-container": "#9d4edd",
        error: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        "body-small": ["Be Vietnam Pro", "system-ui", "sans-serif"],
        h1: ["Epilogue", "system-ui", "sans-serif"],
        h2: ["Epilogue", "system-ui", "sans-serif"],
        body: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        button: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        code: ["JetBrains Mono", "ui-monospace", "SFMono-Regular"],
        outfit: ["Outfit", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
